### ISSUE TITLE
[Firefox & Safari] Clicking focus point is wrong

### ISSUE THREAD

**Issue by binhbbbb** [wiredjs/wired-slider#1]
https://codepen.io/SlashBunny/pen/jGgRoQ?editors=1000
- Tested browser: Firefox Nightly & Safari Tech Preview
![](https://dl.dropbox.com/s/6pe2whgweevoxzx/%5Bbug%5Dwired-slider.gif?dl=0)

**Comment by pshihn** [comment]
Fixed in v0.5.5
https://github.com/wiredjs/wired-slider/commit/13fd11eb3203c20f5e5dd460df629cd7c93709bd
